version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ../../part1/1.12
    depends_on:
      - backend
    ports:
      - 5000:5000

  backend:
    container_name: backend
    build: ../../part1/1.13
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    volumes:
      - ./redis:/data

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ../2.8/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
