version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ../../part1/1.12
    ports:
      - 5000:5000

  backend:
    container_name: backend
    build: ../../part1/1.13
    ports:
      - 8080:8080
